spring:
  application:
    name: user-api
  datasource:
    url: jdbc:mysql://localhost:3306/imooc_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true