server:
  port: 9090
  servlet:
    session:
      timeout: 2592000  #session有效期

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/imooc_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

