zuul:
  routes:
    user:
      url: http://localhost:9090
    token:
      url: http://localhost:9090
    order:
      url: http://localhost:9080
  sensitive-headers:
  ratelimit:
    enabled: true
    repository: JPA
    default-policy-list:
      - limit: 2
        quota: 1
        refresh-interval: 3
        type:
          - url
          - httpmethod
#    policy-list:
#      token:
#        - limit: 2
#          quota: 1
#          refresh-interval: 3
#          type:
#            - url
#            - httpmethod


server:
  port: 9070

spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/imooc_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    show-sql: true

# 网关验证token合法性配置
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://auth.imooc.com:9090/oauth/token_key
    client:
      client-id: gateway
      client-secret: 123456
